//! Generate a typed TypeScript `fetch` API client from the routes
//! collected in an [`OpenApi`] value.
//!
//! This crate keeps using the vocabulary of the Open API specification
//! ([`crate::openapi`]) as its in-memory intermediate representation
//! while routes are walked (paths, operations, parameters, responses,
//! ...), but instead of serializing that representation to an Open API
//! JSON document, this module turns it into TypeScript source code.
//!
//! Getting usable TypeScript out of an [`OpenApi`] value produced by,
//! for example, [`ApiRouter::finish_api`](crate::axum::ApiRouter::finish_api)
//! involves two steps:
//!
//! 1. Export the TypeScript type declarations referenced by the API to
//!    disk with [`crate::generate::export_types`]. Each type gets
//!    written to its own `.ts` file (this is handled by
//!    [`ts-rs`](https://docs.rs/ts-rs)).
//! 2. Render a typed API client from the routes with [`to_client`],
//!    which imports the types generated in step 1.
//!
//! # Example
//!
//! ```
//! use aide::openapi::OpenApi;
//! use aide::typescript::{to_client, TypescriptClientOptions};
//!
//! let api = OpenApi::default();
//! let client = to_client(&api, &TypescriptClientOptions::default());
//! assert!(client.contains("async function request"));
//! ```

use std::collections::BTreeSet;
use std::fmt::Write as _;

use crate::openapi::{OpenApi, Operation, Parameter, ReferenceOr, Response, SchemaObject, StatusCode};

/// Options controlling how [`to_client`] renders the generated code.
#[derive(Debug, Clone)]
pub struct TypescriptClientOptions {
    /// Directory (as a relative import specifier, e.g. `"./"` or
    /// `"../types/"`) under which the types exported via
    /// [`crate::generate::export_types`] can be found.
    ///
    /// `ts-rs` writes one file per type, named after the type (e.g.
    /// `User.ts`), so a type named `User` is imported from
    /// `{types_dir}User`. This should match the `out_dir` passed to
    /// [`crate::generate::export_types`], relative to wherever the
    /// generated client is placed.
    pub types_dir: String,
    /// Base URL prepended to every request path. Left empty by
    /// default, meaning requests are made against relative URLs.
    pub base_url: String,
}

impl Default for TypescriptClientOptions {
    fn default() -> Self {
        Self {
            types_dir: "./".to_owned(),
            base_url: String::new(),
        }
    }
}

/// Generate a typed TypeScript `fetch` API client from the given
/// [`OpenApi`] document.
///
/// The generated module exports one `async` function per operation,
/// named after the operation id (or a name derived from the HTTP
/// method and path if none is set). Each function takes typed
/// `path`/`query`/`body` parameters (only the ones that apply to the
/// operation) and returns the operation's documented success response
/// type.
#[must_use]
pub fn to_client(api: &OpenApi, options: &TypescriptClientOptions) -> String {
    let mut type_names = BTreeSet::new();
    let mut functions = String::new();

    for (path, method, operation) in api.operations() {
        let _ = write!(
            functions,
            "{}\n",
            render_operation(path, method, operation, &mut type_names)
        );
    }

    let mut out = String::new();
    let _ = writeln!(out, "// This file is generated by `aide`. Do not edit by hand.");
    out.push('\n');

    for name in &type_names {
        let _ = writeln!(
            out,
            "import type {{ {name} }} from {:?};",
            format!("{}{name}", options.types_dir)
        );
    }
    if !type_names.is_empty() {
        out.push('\n');
    }

    out.push_str(&preamble(&options.base_url));
    out.push('\n');
    out.push_str(&functions);

    out
}

fn preamble(base_url: &str) -> String {
    format!(
        r#"const BASE_URL = {base_url:?};

async function request<T>(method: string, path: string, body?: unknown, init?: RequestInit): Promise<T> {{
  const res = await fetch(`${{BASE_URL}}${{path}}`, {{
    ...init,
    method,
    headers: {{
      ...(body !== undefined ? {{ "Content-Type": "application/json" }} : {{}}),
      ...(init?.headers ?? {{}}),
    }},
    body: body !== undefined ? JSON.stringify(body) : undefined,
  }});

  if (!res.ok) {{
    throw new Error(`${{method}} ${{path}} failed with status ${{res.status}}`);
  }}

  if (res.status === 204) {{
    return undefined as T;
  }}

  const text = await res.text();
  return (text.length > 0 ? JSON.parse(text) : undefined) as T;
}}
"#,
    )
}

fn render_operation(
    path: &str,
    method: &str,
    operation: &Operation,
    type_names: &mut BTreeSet<String>,
) -> String {
    let fn_name = operation
        .operation_id
        .clone()
        .unwrap_or_else(|| default_fn_name(method, path));

    let path_schema = find_parameter_schema(operation, |p| matches!(p, Parameter::Path { .. }));
    let query_schema = find_parameter_schema(operation, |p| matches!(p, Parameter::Query { .. }));
    let body_schema = operation
        .request_body
        .as_ref()
        .and_then(ReferenceOr::as_item)
        .and_then(|b| preferred_schema(b.content.iter()));
    let response_schema = success_response(operation)
        .and_then(|r| preferred_schema(r.content.iter()));

    for schema in [&path_schema, &query_schema, &body_schema, &response_schema]
        .into_iter()
        .flatten()
    {
        collect_type_idents(&schema.ts_type, type_names);
    }

    let mut params = Vec::new();
    if let Some(schema) = &path_schema {
        params.push(format!("path: {}", schema.ts_type));
    }
    if let Some(schema) = &query_schema {
        params.push(format!("query: {}", schema.ts_type));
    }
    if let Some(schema) = &body_schema {
        params.push(format!("body: {}", schema.ts_type));
    }
    params.push("init?: RequestInit".to_owned());

    let return_ty = response_schema
        .map(|s| s.ts_type)
        .unwrap_or_else(|| "void".to_owned());

    // Note: the local variables below are deliberately named
    // differently from the `path`/`query`/`body` parameters (which
    // would otherwise shadow them and cause a temporal-dead-zone
    // error at runtime, since the shadowing `const` would be
    // referenced by its own initializer).
    let mut body = String::new();
    if query_schema.is_some() {
        let _ = writeln!(
            body,
            "  const basePath = {};",
            path_template(path, path_schema.is_some())
        );
        let _ = writeln!(
            body,
            "  const queryString = new URLSearchParams(query as Record<string, string>).toString();"
        );
        let _ = writeln!(
            body,
            "  const url = queryString.length > 0 ? `${{basePath}}?${{queryString}}` : basePath;"
        );
    } else {
        let _ = writeln!(
            body,
            "  const url = {};",
            path_template(path, path_schema.is_some())
        );
    }

    let body_arg = if body_schema.is_some() { "body" } else { "undefined" };
    let _ = writeln!(
        body,
        "  return request<{return_ty}>({method:?}, url, {body_arg}, init);"
    );

    format!(
        "export async function {fn_name}({params}): Promise<{return_ty}> {{\n{body}}}",
        params = params.join(", "),
    )
}

/// Turn a route path template (e.g. `/users/{id}` or `/users/:id`)
/// into a TypeScript template literal that substitutes path parameters
/// from a `path` object at runtime.
fn path_template(path: &str, has_path_params: bool) -> String {
    if !has_path_params || (!path.contains('{') && !path.contains(':')) {
        return format!("{path:?}");
    }

    let mut out = String::from('`');
    let mut chars = path.chars().peekable();

    while let Some(c) = chars.next() {
        match c {
            '{' => {
                let name: String = chars.by_ref().take_while(|c| *c != '}').collect();
                let _ = write!(out, "${{encodeURIComponent(String((path as any)[{name:?}]))}}");
            }
            ':' if chars
                .peek()
                .is_some_and(|c| c.is_alphanumeric() || *c == '_') =>
            {
                let mut name = String::new();
                while let Some(c) = chars.peek() {
                    if c.is_alphanumeric() || *c == '_' {
                        name.push(*c);
                        chars.next();
                    } else {
                        break;
                    }
                }
                let _ = write!(out, "${{encodeURIComponent(String((path as any)[{name:?}]))}}");
            }
            '`' | '$' | '\\' => {
                out.push('\\');
                out.push(c);
            }
            c => out.push(c),
        }
    }

    out.push('`');
    out
}

fn default_fn_name(method: &str, path: &str) -> String {
    let mut name = method.to_lowercase();

    // Split each path segment on any non-alphanumeric character
    // (`.`, `-`, `:`, `{`, `}`, `/`, ...) so that segments like
    // `private/api.json` or `:user-id` turn into valid, camel-cased
    // TypeScript identifiers instead of containing stray punctuation.
    for word in path.split(|c: char| !c.is_alphanumeric()) {
        if word.is_empty() {
            continue;
        }

        let mut chars = word.chars();
        if let Some(first) = chars.next() {
            name.push(first.to_ascii_uppercase());
            name.extend(chars);
        }
    }

    name
}

fn find_parameter_schema(
    operation: &Operation,
    matches: impl Fn(&Parameter) -> bool,
) -> Option<SchemaObject> {
    operation.parameters.iter().find_map(|p| {
        let p = p.as_item()?;
        if !matches(p) {
            return None;
        }

        match &p.parameter_data_ref().format {
            crate::openapi::ParameterSchemaOrContent::Schema(s) => Some(s.clone()),
            crate::openapi::ParameterSchemaOrContent::Content(_) => None,
        }
    })
}

fn preferred_schema<'a>(
    content: impl Iterator<Item = (&'a String, &'a crate::openapi::MediaType)>,
) -> Option<SchemaObject> {
    let mut entries: Vec<_> = content.collect();
    entries.sort_by_key(|(k, _)| if k.as_str() == "application/json" { 0 } else { 1 });
    entries.into_iter().find_map(|(_, mt)| mt.schema.clone())
}

fn success_response(operation: &Operation) -> Option<&Response> {
    let responses = operation.responses.as_ref()?;

    responses
        .responses
        .iter()
        .find(|(code, _)| is_success(code))
        .and_then(|(_, r)| r.as_item())
        .or_else(|| responses.default.as_ref().and_then(ReferenceOr::as_item))
}

fn is_success(code: &StatusCode) -> bool {
    match code {
        StatusCode::Code(c) => (200..300).contains(c),
        StatusCode::Range(r) => *r == 2,
    }
}

/// TypeScript builtin identifiers that should never be treated as an
/// importable named type.
const TS_BUILTINS: &[&str] = &[
    "string", "number", "boolean", "null", "undefined", "void", "unknown", "any", "never",
    "object", "bigint", "Array", "Record", "Partial", "Required", "Readonly", "Pick", "Omit",
    "Promise", "Date",
];

/// Extract identifier-like tokens from a (possibly generic) TypeScript
/// type expression, e.g. `Array<User>` -> `["User"]`, skipping
/// builtins.
fn collect_type_idents(ts_type: &str, out: &mut BTreeSet<String>) {
    let mut current = String::new();

    let flush = |current: &mut String, out: &mut BTreeSet<String>| {
        if !current.is_empty() {
            if !TS_BUILTINS.contains(&current.as_str()) {
                out.insert(current.clone());
            }
            current.clear();
        }
    };

    for c in ts_type.chars() {
        if c.is_alphanumeric() || c == '_' || c == '$' {
            current.push(c);
        } else {
            flush(&mut current, out);
        }
    }
    flush(&mut current, out);
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::openapi::{
        MediaType, ParameterData, ParameterSchemaOrContent, PathItem, Paths, QueryStyle,
        Responses,
    };
    use indexmap::IndexMap;

    fn schema(ts_type: &str) -> SchemaObject {
        SchemaObject::literal(ts_type)
    }

    #[test]
    fn collects_generic_type_names() {
        let mut names = BTreeSet::new();
        collect_type_idents("Array<User>", &mut names);
        assert_eq!(names, BTreeSet::from(["User".to_owned()]));
    }

    #[test]
    fn renders_path_and_query_and_body() {
        let mut operation = Operation {
            operation_id: Some("createUserPost".to_owned()),
            ..Default::default()
        };

        operation.parameters.push(ReferenceOr::Item(Parameter::Path {
            parameter_data: ParameterData {
                name: "path".into(),
                description: None,
                required: true,
                deprecated: None,
                format: ParameterSchemaOrContent::Schema(schema("UserPath")),
                example: None,
                examples: IndexMap::new(),
                explode: None,
                extensions: IndexMap::new(),
            },
            style: crate::openapi::PathStyle::Simple,
        }));

        operation.parameters.push(ReferenceOr::Item(Parameter::Query {
            parameter_data: ParameterData {
                name: "query".into(),
                description: None,
                required: false,
                deprecated: None,
                format: ParameterSchemaOrContent::Schema(schema("UserQuery")),
                example: None,
                examples: IndexMap::new(),
                explode: None,
                extensions: IndexMap::new(),
            },
            allow_reserved: false,
            style: QueryStyle::Form,
            allow_empty_value: None,
        }));

        operation.request_body = Some(ReferenceOr::Item(crate::openapi::RequestBody {
            description: None,
            content: IndexMap::from_iter([(
                "application/json".to_owned(),
                MediaType {
                    schema: Some(schema("CreateUser")),
                    ..Default::default()
                },
            )]),
            required: true,
            extensions: IndexMap::new(),
        }));

        let mut responses = Responses::default();
        responses.responses.insert(
            StatusCode::Code(200),
            ReferenceOr::Item(Response {
                description: "the created user".into(),
                content: IndexMap::from_iter([(
                    "application/json".to_owned(),
                    MediaType {
                        schema: Some(schema("User")),
                        ..Default::default()
                    },
                )]),
                ..Default::default()
            }),
        );
        operation.responses = Some(responses);

        let api = OpenApi {
            paths: Some(Paths {
                paths: IndexMap::from([(
                    "/users/{id}".to_owned(),
                    ReferenceOr::Item(PathItem {
                        post: Some(operation),
                        ..Default::default()
                    }),
                )]),
                extensions: IndexMap::new(),
            }),
            ..OpenApi::default()
        };

        let client = to_client(&api, &TypescriptClientOptions::default());

        assert!(client.contains("import type { CreateUser } from \"./CreateUser\";"));
        assert!(client.contains("import type { User } from \"./User\";"));
        assert!(client.contains("import type { UserPath } from \"./UserPath\";"));
        assert!(client.contains("import type { UserQuery } from \"./UserQuery\";"));
        assert!(client.contains("export async function createUserPost(path: UserPath, query: UserQuery, body: CreateUser, init?: RequestInit): Promise<User>"));
        assert!(client.contains("(path as any)[\"id\"]"));
    }

    #[test]
    fn default_fn_name_from_method_and_path() {
        assert_eq!(default_fn_name("get", "/users/{id}"), "getUsersId");
        assert_eq!(default_fn_name("post", "/users"), "postUsers");
    }
}
