[package]
name = "example-axum"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
axts = { path = "../../crates/axts", features = [
    "axum-json",
    "macros",
] }
axum = { version = "0.8", features = ["macros"] }
specta = { path = "/home/franco/Projects/FORKS/rust/specta", version = "1", features = ["uuid", "serde"] }
serde = { version = "1", features = ["derive", "rc"] }
serde_json = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
uuid = { version = "1", features = ["serde", "v4"] }
